import httpx
import logging
from datetime import datetime
from typing import Optional

from config import GEMINI_URL, CACHE_TTL_MINUTES, GEMINI_API_KEY

logger = logging.getLogger(__name__)

_analysis_cache: dict[str, dict] = {}

def _is_cache_valid(sector: str) -> bool:
    if sector not in _analysis_cache:
        return False
    cached_at = datetime.fromisoformat(_analysis_cache[sector]["generated_at"])
    age_minutes = (datetime.utcnow() - cached_at).total_seconds() / 60
    return age_minutes < CACHE_TTL_MINUTES


def _build_prompt(sector: str, collected_data: dict) -> str:
    """Build the prompt sent to Gemini."""
    data_points = collected_data.get("data_points", [])

    context_lines = []
    for i, item in enumerate(data_points[:10], 1):
        title = item.get("title", "")[:100]
        body  = item.get("body",  "")[:300]
        context_lines.append(f"{i}. {title}\n   {body}")
    context_str = "\n\n".join(context_lines) if context_lines else "No live data available."

    return f"""
You are an expert trade analyst specialising in the Indian market.

Using the context below, generate a comprehensive **Trade Opportunities Report** 
for the **{sector.upper()}** sector in India.

---
### CONTEXT DATA (gathered {collected_data.get('collected_at', 'recently')})
{context_str}
---

### REPORT STRUCTURE (use this exact Markdown format)

# Trade Opportunities Report: {sector.title()} Sector — India
**Generated:** {datetime.utcnow().strftime('%B %d, %Y')}
**Sector:** {sector.title()}

## Executive Summary
(2–3 sentences summarising the sector's trade outlook)

## Current Market Overview
(Market size, key players, recent performance)

## Export Opportunities
(Top 3–5 specific export opportunities with target markets)

## Import Trends
(Key imports, dependency areas, opportunities for substitution)

## Growth Drivers
(Policy support, demand trends, technology, demographics)

## Key Challenges & Risks
(Regulatory, geopolitical, infrastructure, competition)

## Actionable Recommendations
(3–5 concrete steps for businesses/investors)

## Key Market Indicators
| Indicator | Value / Trend |
|-----------|--------------|
| Market Size | ... |
| YoY Growth | ... |
| Top Export Markets | ... |
| Top Import Sources | ... |

## Conclusion
(Forward-looking summary)

---
*Report generated by Trade Opportunities API | Data sources: Web search aggregation + AI analysis*

---
Generate ONLY the Markdown report. Do not add any preamble or explanation outside the report.
""".strip()


async def analyze_with_gemini(sector: str, collected_data: dict) -> tuple[str, bool]:
    """
    Calls Gemini API to generate a markdown report.
    Returns (markdown_report, was_cached).
    Falls back to a template report if the API key is not set.
    """
    if _is_cache_valid(sector):
        logger.info(f"Cache hit for sector: {sector}")
        return _analysis_cache[sector]["report"], True

    if not GEMINI_API_KEY:
        logger.warning("Gemini API key not set — returning mock report")
        report = _generate_mock_report(sector, collected_data)
        _analysis_cache[sector] = {
            "report": report,
            "generated_at": datetime.utcnow().isoformat()
        }
        return report, False

    prompt = _build_prompt(sector, collected_data)

    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {
            "temperature": 0.7,
            "maxOutputTokens": 2048,
            "topP": 0.9
        }
    }

    try:
        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                GEMINI_URL,
                params={"key": GEMINI_API_KEY},
                json=payload,
                headers={"Content-Type": "application/json"}
            )
            resp.raise_for_status()
            data = resp.json()

        report = (
            data["candidates"][0]["content"]["parts"][0]["text"]
        )
        logger.info(f"Gemini analysis complete for sector: {sector}")

    except httpx.HTTPStatusError as e:
        logger.error(f"Gemini API HTTP error: {e.response.status_code} — {e.response.text}")
        report = _generate_mock_report(sector, collected_data)

    except Exception as e:
        logger.error(f"Gemini API error: {e}")
        report = _generate_mock_report(sector, collected_data)

    _analysis_cache[sector] = {
        "report": report,
        "generated_at": datetime.utcnow().isoformat()
    }
    return report, False


def _generate_mock_report(sector: str, collected_data: dict) -> str:
    """Fallback report when Gemini key is absent or API fails."""
    data_points = collected_data.get("data_points", [])
    snippets = "\n".join(
        f"- {d['body'][:200]}" for d in data_points[:3]
    ) or "- No live data collected."

    return f"""# Trade Opportunities Report: {sector.title()} Sector — India
**Generated:** {datetime.utcnow().strftime('%B %d, %Y')}
**Sector:** {sector.title()}
**Note:** This is a placeholder report. Add your Gemini API key for AI-powered analysis.

## Executive Summary
The {sector} sector in India presents significant trade opportunities driven by
domestic demand growth, supportive government policies, and increasing global
integration.

## Collected Market Snippets
{snippets}

## Export Opportunities
- Emerging markets in Southeast Asia and Africa
- Value-added product exports
- Technology and IP licensing opportunities

## Import Trends
- Raw material imports remain key
- Capital equipment sourcing from developed nations
- Technology transfer agreements

## Growth Drivers
- Government initiatives (Make in India, PLI schemes)
- Rising domestic consumption
- Digital infrastructure expansion

## Key Challenges & Risks
- Global supply chain disruptions
- Regulatory compliance complexity
- Currency volatility

## Actionable Recommendations
1. Leverage PLI scheme benefits for capacity expansion
2. Explore FTA opportunities with target export markets
3. Invest in R&D for value-added product development
4. Strengthen supply chain resilience
5. Engage with export promotion councils

## Key Market Indicators
| Indicator | Value / Trend |
|-----------|--------------|
| Market Size | Growing (see live data) |
| YoY Growth | Positive trajectory |
| Top Export Markets | USA, EU, Middle East |
| Top Import Sources | China, USA, Germany |

## Conclusion
The {sector} sector offers compelling opportunities for businesses willing to
navigate the dynamic Indian trade environment.

---
*Report generated by Trade Opportunities API*
"""