export const SECTORS = [
  { value: 'pharmaceuticals', label: 'Pharmaceuticals',  icon: '💊' },
  { value: 'technology',      label: 'Technology',        icon: '💻' },
  { value: 'agriculture',     label: 'Agriculture',       icon: '🌾' },
  { value: 'automobiles',     label: 'Automobiles',       icon: '🚗' },
  { value: 'textiles',        label: 'Textiles',          icon: '🧵' },
  { value: 'finance',         label: 'Finance',           icon: '💰' },
  { value: 'energy',          label: 'Energy',            icon: '⚡' },
  { value: 'real estate',     label: 'Real Estate',       icon: '🏢' },
  { value: 'healthcare',      label: 'Healthcare',        icon: '🏥' },
  { value: 'manufacturing',   label: 'Manufacturing',     icon: '🏭' },
  { value: 'retail',          label: 'Retail',            icon: '🛒' },
  { value: 'chemicals',       label: 'Chemicals',         icon: '⚗️' },
  { value: 'defence',         label: 'Defence',           icon: '🛡️' },
  { value: 'fmcg',            label: 'FMCG',              icon: '🧴' },
  { value: 'banking',         label: 'Banking',           icon: '🏦' },
  { value: 'telecom',         label: 'Telecom',           icon: '📡' },
  { value: 'infrastructure',  label: 'Infrastructure',    icon: '🏗️' },
  { value: 'education',       label: 'Education',         icon: '📚' },
  { value: 'logistics',       label: 'Logistics',         icon: '🚚' },
  { value: 'it',              label: 'IT',                icon: '🖥️' },
]   
